### ISSUE TITLE
Error message for different column names/column number/layout

### ISSUE THREAD

**Issue by TechSolomon** [TAWinterton2/CS-F600-ML-GUI#62] opened 2023-11-07 01:44 UTC
- `Program returned error while uploading the zip: Could not determine delimiter` with [wdbc.data-multi-csv-different-col-names.zip](https://github.com/TAWinterton2/CS-F600-ML-GUI/files/13285185/wdbc.data-multi-csv-different-col-names.zip) or [wdbc.data-multi-csv-different-col-num.zip](https://github.com/TAWinterton2/CS-F600-ML-GUI/files/13285186/wdbc.data-multi-csv-different-col-num.zip)

-----

- `Program returned error while uploading the zip: 'utf-8' codec can't decode byte 0xdd in position 37: invalid continuation byte` with [heart_data.csv.zip](https://github.com/TAWinterton2/CS-F600-ML-GUI/files/13285173/heart_data.csv.zip)

**Comment by raelewis** [comment] 2023-11-08 22:48
Thanks for catching these! I'm still looking into the delimiter error, but the secondary error appears to have been caused by how we were decoding the uploaded zip file as well as a small issue with handling hidden directories of zip folders. I'll post another update once I've got the fix working for the first error.

**Comment by raelewis** [comment] 2023-11-09 00:28
The delimiter error was caused due to how we were checking for file headers in the zip_unpack function. We've updated both this function and csv_upload to adjust how the file contents are read by csv.Sniffer.has_header. These zip folders should now properly display the correct error.

**Comment by TAWinterton2** [comment] 2023-11-14 22:30
Patch 1 Successful Merge. Closing issue.

**Closed by TAWinterton2** 2023-11-14 22:30 UTC
Labels: documentation, error message
